"""Static command overview rendering kept separate from CLI dispatch."""


def print_command_overview() -> None:
    """Print a comprehensive overview of all available commands."""
    print("🚀 Entrix 可执行质量门禁系统")
    print("=" * 60)
    print()
    print("📋 基础命令:")
    print("  /entrix init")
    print("      初始化 .mcp.json 与 harness.yaml 配置文件")
    print("      示例: /entrix init --profile python")
    print("  /entrix run")
    print("      运行质量检查（快速检查）")
    print("      示例: /entrix run --tier fast")
    print("  /entrix harness validate")
    print("      验证 harness.yaml 配置文件正确性")
    print("      示例: /entrix harness validate")
    print("  /entrix harness run")
    print("      执行完整的 Harness 检查和门禁裁决")
    print("      示例: /entrix harness run --json")
    print()
    print("常用命令：")
    print("  entrix init                 初始化 .mcp.json 与 harness.yaml")
    print("  entrix phase planning      标记当前回合为规划阶段")
    print("  entrix harness validate     检查 Harness 配置")
    print("  entrix run                  执行 Fitness 指标")
    print("  entrix harness run --json   收集 evidence 并执行门禁裁决")
    print("  entrix review-trigger       识别需要人工审查的改动")
    print("  entrix stop-gate            作为 Claude Code Stop Hook 执行")
    print("  entrix serve                启动 MCP 服务")
    print()
    print("🔄 阶段管理:")
    print("  /entrix phase planning")
    print("      标记当前回合为规划阶段")
    print("      用于头脑风暴和架构设计阶段")
    print("  /entrix phase implementation")
    print("      标记当前回合为实现阶段")
    print("      用于代码实现和测试阶段")
    print()
    print("🔍 分析和审查:")
    print("  /entrix review-trigger")
    print("      识别需要人工审查的变更")
    print("      检查核心文件修改和大规模变更")
    print("  /entrix release-trigger")
    print("      检查发布表面的风险变更")
    print("      在发布前验证关键组件状态")
    print()
    print("🛡️  Stop Gate:")
    print("  /entrix stop-gate")
    print("      作为 Claude Code Stop Hook 执行")
    print("      自动阻止不符合质量标准的提交")
    print()
    print("🔧 开发者工具:")
    print("  /entrix serve")
    print("      启动 MCP 服务用于集成")
    print("  /entrix graph build")
    print("      构建代码影响分析图")
    print("  /entrix analyze long-file")
    print("      分析长文件的影响和建议")
    print()
    print("⚙️  常用选项:")
    print("  --repo <path>        指定仓库路径")
    print("  --profile <name>     语言配置 (python|node-typescript|java-maven|go|rust)")
    print("  --tier fast|normal    执行层级")
    print("  --json               JSON 格式输出")
    print()
    print("🎯 可配置 Lint 系统:")
    print("  Entrix 现在支持通过 YAML 配置自定义 lint 工具")
    print("  配置文件: .claude/lint-config.yaml")
    print("  支持语言: Python, TypeScript, Java, Go, Rust")
    print()
    print("🚀 快速开始:")
    print("  首次使用:   /entrix init --profile auto")
    print("  日常检查:   /entrix run --tier fast")
    print("  完整检查:   /entrix run")
    print("  查看配置:   vim .claude/lint-config.yaml")
    print()
    print("=" * 60)
    print("💡 提示: 使用 --help 查看每个命令的详细选项")
    print("📖 详细文档: docs/command-reference.md")


def show_subgroup_help(subgroup: str) -> None:
    """显示子命令组的帮助信息。"""
    if subgroup == "harness":
        print("🔧 Harness 子命令:")
        print("  validate     检查 Harness 配置正确性")
        print("  run          执行完整的 Harness 检查")
        print()
        print("示例:")
        print("  entrix harness validate")
        print("  entrix harness run --json")
    elif subgroup == "graph":
        print("📊 Graph 子命令:")
        print("  build        构建代码影响分析图")
        print("  stats        显示图统计信息")
        print("  impact        分析变更影响范围 (impact)")
        print("  test-radius  分析测试覆盖率")
        print("  test-mapping 分析测试映射关系")
        print("  query        运行图查询")
        print("  history      分析提交历史")
        print("  review-context 分析审查上下文")
        print()
        print("示例:")
        print("  entrix graph build")
        print("  entrix graph impact <file>")
    elif subgroup == "hook":
        print("🔧 Hook 子命令:")
        print("  file-length  检查文件长度")
        print()
        print("示例:")
        print("  entrix hook file-length <file>")
    elif subgroup == "analyze":
        print("🔍 Analyze 子命令:")
        print("  long-file    分析长文件")
        print()
        print("示例:")
        print("  entrix analyze long-file <file>")
    else:
        print(f"未知子命令组: {subgroup}")
